import Head from "next/head";
import Link from "next/link";
import { Box, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Devis sports</title>
        <meta
          name="description"
          content="Devix sports - Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          textAlign: "center",
        }}
      >
        <Typography variant="h1">This is Home page</Typography>
        <Typography component={Link} variant="h3" href="/results">
          Click here for results
        </Typography>
      </Box>
    </>
  );
}
